// CHECKSTYLE:OFF -- we can't help it's a long file checkstyle.
/**
 * Copyright (C) 2014-Present McLeod Moores Software Limited.  All rights reserved.
 */
package com.mcleodmoores.excel4j.simulator;

import com.mcleodmoores.excel4j.ExcelFunctionCallHandler;
import com.mcleodmoores.excel4j.values.XLValue;

/**
 * Class to mock the DLL exports table.
 */
public class MockDLLExports {
  
  private ExcelFunctionCallHandler _callHandler;
  /**
   * Constructor.
   * @param callHandler  the call handler for invoking methods
   */
  public MockDLLExports(final ExcelFunctionCallHandler callHandler) {
    _callHandler = callHandler;
  }
  // CHECKSTYLE:OFF -- autogenerated.
  public XLValue UDF_0(final XLValue... args) {
    return UDF(0, args);
  }

  public XLValue UDF_1(final XLValue... args) {
    return UDF(1, args);
  }

  public XLValue UDF_2(final XLValue... args) {
    return UDF(2, args);
  }

  public XLValue UDF_3(final XLValue... args) {
    return UDF(3, args);
  }

  public XLValue UDF_4(final XLValue... args) {
    return UDF(4, args);
  }

  public XLValue UDF_5(final XLValue... args) {
    return UDF(5, args);
  }

  public XLValue UDF_6(final XLValue... args) {
    return UDF(6, args);
  }

  public XLValue UDF_7(final XLValue... args) {
    return UDF(7, args);
  }

  public XLValue UDF_8(final XLValue... args) {
    return UDF(8, args);
  }

  public XLValue UDF_9(final XLValue... args) {
    return UDF(9, args);
  }

  public XLValue UDF_10(final XLValue... args) {
    return UDF(10, args);
  }

  public XLValue UDF_11(final XLValue... args) {
    return UDF(11, args);
  }

  public XLValue UDF_12(final XLValue... args) {
    return UDF(12, args);
  }

  public XLValue UDF_13(final XLValue... args) {
    return UDF(13, args);
  }

  public XLValue UDF_14(final XLValue... args) {
    return UDF(14, args);
  }

  public XLValue UDF_15(final XLValue... args) {
    return UDF(15, args);
  }

  public XLValue UDF_16(final XLValue... args) {
    return UDF(16, args);
  }

  public XLValue UDF_17(final XLValue... args) {
    return UDF(17, args);
  }

  public XLValue UDF_18(final XLValue... args) {
    return UDF(18, args);
  }

  public XLValue UDF_19(final XLValue... args) {
    return UDF(19, args);
  }

  public XLValue UDF_20(final XLValue... args) {
    return UDF(20, args);
  }

  public XLValue UDF_21(final XLValue... args) {
    return UDF(21, args);
  }

  public XLValue UDF_22(final XLValue... args) {
    return UDF(22, args);
  }

  public XLValue UDF_23(final XLValue... args) {
    return UDF(23, args);
  }

  public XLValue UDF_24(final XLValue... args) {
    return UDF(24, args);
  }

  public XLValue UDF_25(final XLValue... args) {
    return UDF(25, args);
  }

  public XLValue UDF_26(final XLValue... args) {
    return UDF(26, args);
  }

  public XLValue UDF_27(final XLValue... args) {
    return UDF(27, args);
  }

  public XLValue UDF_28(final XLValue... args) {
    return UDF(28, args);
  }

  public XLValue UDF_29(final XLValue... args) {
    return UDF(29, args);
  }

  public XLValue UDF_30(final XLValue... args) {
    return UDF(30, args);
  }

  public XLValue UDF_31(final XLValue... args) {
    return UDF(31, args);
  }
  
  public XLValue UDF_32(final XLValue... args) {
    return UDF(32, args);
  }

  public XLValue UDF_33(final XLValue... args) {
    return UDF(33, args);
  }

  public XLValue UDF_34(final XLValue... args) {
    return UDF(34, args);
  }

  public XLValue UDF_35(final XLValue... args) {
    return UDF(35, args);
  }

  public XLValue UDF_36(final XLValue... args) {
    return UDF(36, args);
  }

  public XLValue UDF_37(final XLValue... args) {
    return UDF(37, args);
  }

  public XLValue UDF_38(final XLValue... args) {
    return UDF(38, args);
  }

  public XLValue UDF_39(final XLValue... args) {
    return UDF(39, args);
  }

  public XLValue UDF_40(final XLValue... args) {
    return UDF(40, args);
  }

  public XLValue UDF_41(final XLValue... args) {
    return UDF(41, args);
  }

  public XLValue UDF_42(final XLValue... args) {
    return UDF(42, args);
  }

  public XLValue UDF_43(final XLValue... args) {
    return UDF(43, args);
  }

  public XLValue UDF_44(final XLValue... args) {
    return UDF(44, args);
  }

  public XLValue UDF_45(final XLValue... args) {
    return UDF(45, args);
  }

  public XLValue UDF_46(final XLValue... args) {
    return UDF(46, args);
  }

  public XLValue UDF_47(final XLValue... args) {
    return UDF(47, args);
  }

  public XLValue UDF_48(final XLValue... args) {
    return UDF(48, args);
  }

  public XLValue UDF_49(final XLValue... args) {
    return UDF(49, args);
  }

  public XLValue UDF_50(final XLValue... args) {
    return UDF(50, args);
  }

  public XLValue UDF_51(final XLValue... args) {
    return UDF(51, args);
  }

  public XLValue UDF_52(final XLValue... args) {
    return UDF(52, args);
  }

  public XLValue UDF_53(final XLValue... args) {
    return UDF(53, args);
  }

  public XLValue UDF_54(final XLValue... args) {
    return UDF(54, args);
  }

  public XLValue UDF_55(final XLValue... args) {
    return UDF(55, args);
  }

  public XLValue UDF_56(final XLValue... args) {
    return UDF(56, args);
  }

  public XLValue UDF_57(final XLValue... args) {
    return UDF(57, args);
  }

  public XLValue UDF_58(final XLValue... args) {
    return UDF(58, args);
  }

  public XLValue UDF_59(final XLValue... args) {
    return UDF(59, args);
  }

  public XLValue UDF_60(final XLValue... args) {
    return UDF(60, args);
  }

  public XLValue UDF_61(final XLValue... args) {
    return UDF(61, args);
  }

  public XLValue UDF_62(final XLValue... args) {
    return UDF(62, args);
  }
  
  public XLValue UDF_63(final XLValue... args) {
    return UDF(63, args);
  }
  public XLValue UDF(final int block, final XLValue... args) {
    return _callHandler.invoke(block, args);
  }
}
