/*
* JVM as a COM object
*
* Copyright 2014 by Andrew Ian William Griffin <griffin@beerdragon.co.uk>
* Released under the GNU General Public License.
*/

import "unknwn.idl";
import "oaidl.idl";

typedef
[
	uuid(dff6d900-b72f-4f06-a1ad-0466ad25c352),
	version(1.0),
	helpstring("Information about a UDF")
]
struct FUNCTIONINFO {
	int exportNumber;
	BSTR functionExportName;
	BSTR functionSignature;
	BSTR functionWorksheetName;
	BSTR argumentNames;
	int functionType;
	BSTR functionCategory;
	BSTR acceleratorKey;
	BSTR helpTopic;
	BSTR description;
	SAFEARRAY (BSTR) argsHelp;
} FUNCTIONINFO;

[
	object,
	uuid(1edb5111-1544-4a2c-b99e-b65e5813a48a)
]
interface IXLCall : IUnknown {
	//[vararg] 
	//	HRESULT call ([in] int iFunctionNum, [in] SAFEARRAY (VARIANT) *args, [out, retval] XL4JOPER12 *result);
	HRESULT scan ([in] FUNCTIONINFO *result);
}

[
	uuid (0e07a0b8-0fa3-4497-bc66-6d2af2a0b9c8),
	helpstring ("Core JVM Support 1.0 Type Library"),
	version (1.0)
] library ComJvmCore {
	interface IXLCall;
	//[
	//	uuid (34b9de97-d756-4d18-a65c-e7a688cdf3e7),
	//	helpstring ("Library entry point"),
	//] coclass JvmSupport {
	//	[default] interface IJvmSupport;
	//};

};