/*
 * JVM as a COM object
 *
 * Copyright 2014 by Andrew Ian William Griffin <griffin@beerdragon.co.uk>
 * Released under the GNU General Public License.
 */

[
	uuid (543e6036-0fe1-4b46-9165-a01cd13c4bd2),
	helpstring ("Local JVM Support 1.0 Type Library"),
	version (1.0)
] library ComJvmLocal {
	importlib ("core.tlb");
	[
		uuid (8a3ec9e1-22b1-471a-acc6-c03849608a2e),
		helpstring ("In-process JVM"),
	] coclass LocalJvmConnector {
		[default] interface IJvmConnector;
	};
};
