/**
 * Copyright (C) 2014-Present McLeod Moores Software Limited.  All rights reserved.
 */
package com.mcleodmoores.excel4j.javacode;

import java.math.BigDecimal;
import java.math.BigInteger;

import org.threeten.bp.LocalDate;

import com.mcleodmoores.excel4j.XLFunction;

/**
 * Class containing various combinations of parameter types.
 */
public class TestMethods {
  
  // CHECKSTYLE:OFF -- autogenerated.  
  public enum MyEnum { A, B };
  public class MyClass {};
  @XLFunction
  public LocalDate method0(String paramName0, Double paramName1) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public void method1(Short paramName0, Character paramName1) { return ; }

  @XLFunction(isAsynchronous=true)
  public Double method2() { return null; }

  @XLFunction
  public LocalDate method3(double paramName0, MyClass paramName1, LocalDate paramName2, MyClass paramName3, Boolean paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public BigInteger method4(LocalDate paramName0, double paramName1, int paramName2, BigInteger paramName3) { return null; }

  @XLFunction
  public MyClass method5(boolean paramName0, MyClass paramName1, Integer paramName2, MyClass paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public double method6(Character paramName0) { return 0d; }

  @XLFunction(isAsynchronous=true)
  public BigDecimal method7(LocalDate paramName0, long paramName1, MyEnum paramName2, Byte paramName3, Float paramName4) { return null; }

  @XLFunction
  public BigDecimal method8() { return null; }

  @XLFunction(isAsynchronous=false)
  public MyEnum method9(Long paramName0, LocalDate paramName1, LocalDate paramName2, BigDecimal paramName3, short paramName4, BigDecimal paramName5, Long paramName6) { return null; }

  @XLFunction
  public int method10(Short paramName0) { return 0; }

  @XLFunction(isAsynchronous=true)
  public Long method11(Integer paramName0, Long paramName1, short paramName2, String paramName3) { return null; }

  @XLFunction
  public float method12(Float paramName0, Float paramName1, Short paramName2, short paramName3) { return 0f; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public int method13(BigDecimal paramName0, LocalDate paramName1) { return 0; }

  @XLFunction
  public Boolean method14(long paramName0) { return null; }

  @XLFunction(isAsynchronous=false)
  public int method15(short paramName0, Byte paramName1, Object paramName2, Character paramName3, Float paramName4, Character paramName5) { return 0; }

  @XLFunction
  public Long method16(Character paramName0, BigInteger paramName1, Float paramName2, MyClass paramName3, Long paramName4, Short paramName5, byte paramName6) { return null; }

  @XLFunction
  public Character method17(MyClass paramName0, char paramName1, Byte paramName2, char paramName3, Integer paramName4, short paramName5, Byte paramName6) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public void method18(BigInteger paramName0, byte paramName1) { return ; }

  @XLFunction(isAsynchronous=true)
  public boolean method19(String paramName0, Object paramName1, int paramName2, Short paramName3, int paramName4, Object paramName5) { return true; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public char method20(Boolean paramName0, long paramName1, Float paramName2) { return 'x'; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public LocalDate method21(String paramName0, Boolean paramName1, Short paramName2, LocalDate paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Integer method22(String paramName0, float paramName1, LocalDate paramName2, char paramName3, byte paramName4) { return null; }

  @XLFunction(isAsynchronous=true)
  public String method23(Boolean paramName0, MyClass paramName1, Long paramName2) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public MyClass method24(byte paramName0, Short paramName1, Double paramName2, float paramName3, MyEnum paramName4) { return null; }

  @XLFunction
  public double method25(Boolean paramName0, Short paramName1, String paramName2, Character paramName3, Float paramName4, Float paramName5, BigInteger paramName6) { return 0d; }

  @XLFunction(isAsynchronous=true)
  public MyEnum method26(BigDecimal paramName0) { return null; }

  @XLFunction
  public byte method27(Object paramName0, Byte paramName1, Float paramName2, Character paramName3, Double paramName4) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public Double method28(String paramName0) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Character method29(Character paramName0, int paramName1, BigInteger paramName2, MyEnum paramName3) { return null; }

  @XLFunction(isAsynchronous=true)
  public BigDecimal method30(Boolean paramName0, MyEnum paramName1, Integer paramName2, long paramName3, BigInteger paramName4) { return null; }

  @XLFunction
  public Short method31(Byte paramName0, byte paramName1, long paramName2, byte paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public char method32(Double paramName0, String paramName1, Double paramName2) { return 'x'; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public long method33(short paramName0, Integer paramName1) { return 0L; }

  @XLFunction
  public Short method34(LocalDate paramName0, Object paramName1, Long paramName2, long paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public BigDecimal method35(Short paramName0, Short paramName1, float paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public LocalDate method36() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public char method37(Byte paramName0, int paramName1, Object paramName2, String paramName3, String paramName4, MyEnum paramName5) { return 'x'; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Long method38(short paramName0, String paramName1, Object paramName2) { return null; }

  @XLFunction
  public Object method39(Double paramName0, BigInteger paramName1, char paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Integer method40(Long paramName0, Integer paramName1) { return null; }

  @XLFunction(isAsynchronous=true)
  public Double method41(BigDecimal paramName0, float paramName1, double paramName2, MyEnum paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public byte method42(boolean paramName0, float paramName1, long paramName2, Object paramName3, short paramName4) { return 0; }

  @XLFunction(isAsynchronous=false)
  public BigDecimal method43(Integer paramName0, byte paramName1, double paramName2, BigInteger paramName3, boolean paramName4, Boolean paramName5, Integer paramName6) { return null; }

  @XLFunction
  public Character method44(short paramName0, Float paramName1, float paramName2) { return null; }

  @XLFunction(isAsynchronous=true)
  public Byte method45(Short paramName0) { return null; }

  @XLFunction
  public Integer method46(short paramName0, Character paramName1, LocalDate paramName2, Integer paramName3, Short paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Object method47() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public int method48(Long paramName0, short paramName1, LocalDate paramName2, byte paramName3, MyClass paramName4, Object paramName5, Character paramName6) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public double method49(short paramName0, Float paramName1) { return 0d; }

  @XLFunction(isAsynchronous=true)
  public BigDecimal method50(byte paramName0, double paramName1) { return null; }

  @XLFunction
  public Boolean method51(BigDecimal paramName0) { return null; }

  @XLFunction(isAsynchronous=true)
  public char method52(float paramName0, String paramName1, Short paramName2) { return 'x'; }

  @XLFunction
  public Integer method53(Boolean paramName0, short paramName1, MyEnum paramName2, Character paramName3, short paramName4, double paramName5) { return null; }

  @XLFunction
  public int method54(Short paramName0, Short paramName1, int paramName2) { return 0; }

  @XLFunction
  public BigInteger method55(String paramName0, Object paramName1, Integer paramName2, Integer paramName3, char paramName4, Integer paramName5, MyEnum paramName6) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public byte method56(Double paramName0, String paramName1, Byte paramName2, boolean paramName3, boolean paramName4) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Short method57() { return null; }

  @XLFunction(isAsynchronous=false)
  public float method58(MyClass paramName0, char paramName1, Short paramName2, BigInteger paramName3, double paramName4, char paramName5) { return 0f; }

  @XLFunction(isAsynchronous=true)
  public boolean method59(Byte paramName0, MyEnum paramName1) { return true; }

  @XLFunction
  public void method60(Long paramName0, Short paramName1, float paramName2, Byte paramName3, LocalDate paramName4, String paramName5) { return ; }

  @XLFunction(isAsynchronous=false)
  public float method61(byte paramName0, double paramName1, long paramName2, MyEnum paramName3) { return 0f; }

  @XLFunction
  public Boolean method62(int paramName0, byte paramName1, MyEnum paramName2, Object paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public long method63(boolean paramName0, LocalDate paramName1, String paramName2, byte paramName3, long paramName4) { return 0L; }

  @XLFunction
  public Boolean method64(BigInteger paramName0, Byte paramName1, byte paramName2) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public byte method65(Character paramName0, Float paramName1, Short paramName2, short paramName3) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public MyEnum method66() { return null; }

  @XLFunction
  public Short method67(long paramName0, Object paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public Object method68(MyClass paramName0, Character paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public String method69(double paramName0, MyClass paramName1, LocalDate paramName2, BigDecimal paramName3, boolean paramName4, MyClass paramName5, Float paramName6) { return null; }

  @XLFunction
  public int method70(int paramName0, boolean paramName1, short paramName2, Double paramName3, Float paramName4, Float paramName5, Float paramName6) { return 0; }

  @XLFunction(isAsynchronous=false)
  public float method71(MyEnum paramName0, LocalDate paramName1) { return 0f; }

  @XLFunction(isAsynchronous=false)
  public long method72(Boolean paramName0, BigInteger paramName1, BigDecimal paramName2, Integer paramName3, Float paramName4) { return 0L; }

  @XLFunction
  public int method73() { return 0; }

  @XLFunction
  public LocalDate method74(MyEnum paramName0, MyClass paramName1, byte paramName2) { return null; }

  @XLFunction
  public String method75(Short paramName0, Integer paramName1, BigDecimal paramName2, Byte paramName3, MyClass paramName4, int paramName5, Boolean paramName6) { return null; }

  @XLFunction
  public int method76() { return 0; }

  @XLFunction
  public byte method77(long paramName0, Boolean paramName1, Float paramName2, MyEnum paramName3) { return 0; }

  @XLFunction(isAsynchronous=false)
  public MyEnum method78(BigDecimal paramName0, Long paramName1, double paramName2, Object paramName3) { return null; }

  @XLFunction
  public Short method79(Long paramName0, float paramName1, char paramName2, Object paramName3, int paramName4, LocalDate paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public BigDecimal method80(BigInteger paramName0, Integer paramName1, int paramName2, Short paramName3, boolean paramName4, BigInteger paramName5, byte paramName6) { return null; }

  @XLFunction(isAsynchronous=true)
  public Float method81(Double paramName0, Character paramName1) { return null; }

  @XLFunction
  public short method82(Long paramName0, Double paramName1) { return 0; }

  @XLFunction
  public Float method83(boolean paramName0) { return null; }

  @XLFunction
  public Byte method84() { return null; }

  @XLFunction(isAsynchronous=true)
  public short method85(Integer paramName0, double paramName1, short paramName2, BigDecimal paramName3, Object paramName4, Byte paramName5, long paramName6) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Object method86(BigInteger paramName0, Float paramName1, Character paramName2, Integer paramName3, Float paramName4) { return null; }

  @XLFunction(isAsynchronous=true)
  public BigDecimal method87(char paramName0, Object paramName1, Double paramName2, Object paramName3) { return null; }

  @XLFunction(isAsynchronous=true)
  public Double method88(Long paramName0, float paramName1, Character paramName2, double paramName3, MyClass paramName4, BigDecimal paramName5, Integer paramName6) { return null; }

  @XLFunction(isAsynchronous=true)
  public double method89(Character paramName0, MyClass paramName1, Double paramName2, MyClass paramName3, Integer paramName4, double paramName5) { return 0d; }

  @XLFunction
  public Character method90(Boolean paramName0, Long paramName1, Integer paramName2, char paramName3, MyEnum paramName4) { return null; }

  @XLFunction(isAsynchronous=false)
  public float method91(short paramName0, Double paramName1, Character paramName2) { return 0f; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Short method92(int paramName0, BigDecimal paramName1, Double paramName2, Byte paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public char method93(Boolean paramName0) { return 'x'; }

  @XLFunction(isAsynchronous=false)
  public Boolean method94(short paramName0, MyEnum paramName1) { return null; }

  @XLFunction
  public Long method95(long paramName0, Byte paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public BigDecimal method96(Double paramName0, Double paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public boolean method97(Character paramName0, char paramName1) { return true; }

  @XLFunction(isAsynchronous=true)
  public double method98(Boolean paramName0, char paramName1, short paramName2, LocalDate paramName3, MyClass paramName4, Float paramName5) { return 0d; }

  @XLFunction(isAsynchronous=true)
  public short method99(boolean paramName0, Long paramName1, Object paramName2, Character paramName3, double paramName4) { return 0; }

  @XLFunction(isAsynchronous=false)
  public MyEnum method100() { return null; }

  @XLFunction(isAsynchronous=false)
  public short method101(char paramName0, double paramName1, byte paramName2) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Long method102(double paramName0, Boolean paramName1, short paramName2, long paramName3, Long paramName4) { return null; }

  @XLFunction
  public Integer method103(byte paramName0) { return null; }

  @XLFunction
  public Byte method104(Float paramName0, double paramName1, Float paramName2, Object paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public double method105(byte paramName0, int paramName1, long paramName2) { return 0d; }

  @XLFunction(isAsynchronous=true)
  public Boolean method106(byte paramName0, int paramName1, Object paramName2, float paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public long method107(int paramName0) { return 0L; }

  @XLFunction
  public Long method108(String paramName0, Boolean paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public int method109(BigInteger paramName0, float paramName1, Object paramName2, String paramName3) { return 0; }

  @XLFunction
  public Integer method110(Character paramName0, byte paramName1, Double paramName2, boolean paramName3, char paramName4, String paramName5, BigDecimal paramName6) { return null; }

  @XLFunction
  public float method111(char paramName0, Integer paramName1, Short paramName2, BigInteger paramName3, Long paramName4) { return 0f; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public BigDecimal method112() { return null; }

  @XLFunction(isAsynchronous=false)
  public Long method113(int paramName0, MyClass paramName1, boolean paramName2, BigDecimal paramName3, Double paramName4, int paramName5, char paramName6) { return null; }

  @XLFunction
  public Double method114(boolean paramName0, boolean paramName1, Byte paramName2, Boolean paramName3, boolean paramName4) { return null; }

  @XLFunction
  public MyClass method115(MyEnum paramName0, byte paramName1, BigDecimal paramName2) { return null; }

  @XLFunction(isAsynchronous=true)
  public int method116(Object paramName0, long paramName1, short paramName2) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public short method117(byte paramName0, long paramName1, byte paramName2) { return 0; }

  @XLFunction
  public double method118(String paramName0, Long paramName1) { return 0d; }

  @XLFunction(isAsynchronous=true)
  public MyEnum method119(Integer paramName0, char paramName1, BigInteger paramName2, long paramName3, LocalDate paramName4, Boolean paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public int method120(Long paramName0, char paramName1, String paramName2, MyEnum paramName3, long paramName4, long paramName5, short paramName6) { return 0; }

  @XLFunction
  public Boolean method121(MyEnum paramName0, boolean paramName1, MyClass paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public MyEnum method122(int paramName0) { return null; }

  @XLFunction
  public Integer method123(long paramName0, BigDecimal paramName1) { return null; }

  @XLFunction(isAsynchronous=true)
  public Short method124(Double paramName0, String paramName1, String paramName2, Double paramName3, Character paramName4, MyClass paramName5, Float paramName6) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public byte method125(Object paramName0, MyEnum paramName1) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public String method126(Byte paramName0, long paramName1, long paramName2, Short paramName3) { return null; }

  @XLFunction
  public LocalDate method127() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public double method128() { return 0d; }

  @XLFunction
  public void method129(Short paramName0) { return ; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public boolean method130(String paramName0, int paramName1, int paramName2, LocalDate paramName3, short paramName4, Long paramName5) { return true; }

  @XLFunction
  public char method131(boolean paramName0, BigDecimal paramName1, LocalDate paramName2, Boolean paramName3) { return 'x'; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Boolean method132(boolean paramName0) { return null; }

  @XLFunction(isAsynchronous=true)
  public byte method133() { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public Integer method134(int paramName0) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Short method135() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public int method136(int paramName0, Long paramName1, LocalDate paramName2, Boolean paramName3, Character paramName4, MyEnum paramName5, Byte paramName6) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Float method137(Short paramName0, short paramName1, Short paramName2, Character paramName3, Double paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public void method138() { return ; }

  @XLFunction
  public char method139() { return 'x'; }

  @XLFunction(isAsynchronous=true)
  public void method140(byte paramName0, double paramName1, Long paramName2, int paramName3, String paramName4, Long paramName5, BigInteger paramName6) { return ; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Long method141(Short paramName0) { return null; }

  @XLFunction
  public Long method142(String paramName0, MyEnum paramName1, String paramName2, Boolean paramName3, Integer paramName4, MyClass paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Double method143() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public boolean method144(Float paramName0, Integer paramName1, Long paramName2, Long paramName3, Integer paramName4, BigDecimal paramName5, BigInteger paramName6) { return true; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Long method145(String paramName0, double paramName1, double paramName2, Boolean paramName3, float paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public BigInteger method146(Float paramName0, float paramName1, boolean paramName2, Integer paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public LocalDate method147(BigInteger paramName0) { return null; }

  @XLFunction
  public LocalDate method148(Boolean paramName0, MyEnum paramName1, Boolean paramName2, int paramName3, float paramName4, Float paramName5, Byte paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Byte method149() { return null; }

  @XLFunction(isAsynchronous=false)
  public Integer method150(Float paramName0, Float paramName1, double paramName2, Boolean paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public short method151(Character paramName0, Character paramName1, char paramName2) { return 0; }

  @XLFunction
  public String method152(char paramName0, char paramName1, String paramName2, boolean paramName3, BigDecimal paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Character method153() { return null; }

  @XLFunction
  public String method154(Character paramName0, Integer paramName1, Boolean paramName2, float paramName3, byte paramName4, double paramName5) { return null; }

  @XLFunction(isAsynchronous=false)
  public Short method155(MyEnum paramName0, int paramName1, byte paramName2, boolean paramName3, Byte paramName4, char paramName5, long paramName6) { return null; }

  @XLFunction
  public MyEnum method156(String paramName0, MyEnum paramName1, byte paramName2, boolean paramName3, double paramName4, float paramName5, Double paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public BigInteger method157(MyClass paramName0, LocalDate paramName1, Character paramName2, float paramName3, short paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Integer method158() { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public byte method159(MyClass paramName0, double paramName1, Object paramName2, Byte paramName3, Float paramName4) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public Integer method160(Object paramName0, Character paramName1, float paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public float method161(short paramName0) { return 0f; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Byte method162(boolean paramName0, BigInteger paramName1, double paramName2, Float paramName3, char paramName4) { return null; }

  @XLFunction
  public float method163(String paramName0) { return 0f; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Object method164(Long paramName0, LocalDate paramName1) { return null; }

  @XLFunction(isAsynchronous=true)
  public BigInteger method165(BigInteger paramName0, Integer paramName1, Boolean paramName2, Long paramName3, double paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Character method166() { return null; }

  @XLFunction(isAsynchronous=false)
  public Object method167(MyClass paramName0, LocalDate paramName1, String paramName2, Long paramName3, Boolean paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public Short method168(Byte paramName0, Byte paramName1, boolean paramName2, float paramName3, MyEnum paramName4, Float paramName5) { return null; }

  @XLFunction(isAsynchronous=false)
  public Boolean method169(BigInteger paramName0, float paramName1, Double paramName2, MyEnum paramName3, Double paramName4, Short paramName5) { return null; }

  @XLFunction(isAsynchronous=false)
  public BigInteger method170(Object paramName0, Character paramName1, Character paramName2, Short paramName3, LocalDate paramName4, MyEnum paramName5, int paramName6) { return null; }

  @XLFunction(isAsynchronous=false)
  public Byte method171(byte paramName0, Character paramName1, int paramName2, LocalDate paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Float method172(Object paramName0, Boolean paramName1, MyEnum paramName2) { return null; }

  @XLFunction
  public void method173(Integer paramName0) { return ; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public String method174(Boolean paramName0, Double paramName1, float paramName2, char paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public Double method175(MyClass paramName0, Float paramName1, String paramName2, long paramName3, byte paramName4, MyEnum paramName5, Double paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Integer method176(Long paramName0, Boolean paramName1, char paramName2, double paramName3, Double paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public short method177(Float paramName0, Short paramName1, Boolean paramName2, MyClass paramName3, LocalDate paramName4, MyEnum paramName5, BigInteger paramName6) { return 0; }

  @XLFunction
  public Double method178(Byte paramName0, Long paramName1, Long paramName2, Double paramName3, short paramName4) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public Integer method179(String paramName0, Boolean paramName1) { return null; }

  @XLFunction(isAsynchronous=false)
  public Float method180(String paramName0, MyEnum paramName1, Boolean paramName2) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public LocalDate method181() { return null; }

  @XLFunction(isAsynchronous=false)
  public Short method182(Character paramName0, int paramName1, boolean paramName2, Byte paramName3, byte paramName4) { return null; }

  @XLFunction
  public long method183(Integer paramName0) { return 0L; }

  @XLFunction
  public byte method184(long paramName0, float paramName1, Character paramName2) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public BigInteger method185(double paramName0, String paramName1, Float paramName2, byte paramName3, Object paramName4, char paramName5, Float paramName6) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public BigDecimal method186(byte paramName0, Byte paramName1, Long paramName2) { return null; }

  @XLFunction(isAsynchronous=true)
  public byte method187(byte paramName0, Integer paramName1, Long paramName2) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Float method188(Boolean paramName0, BigDecimal paramName1, long paramName2, MyEnum paramName3, Float paramName4, MyEnum paramName5, MyClass paramName6) { return null; }

  @XLFunction
  public Byte method189(LocalDate paramName0, Float paramName1, Integer paramName2) { return null; }

  @XLFunction(isAsynchronous=false)
  public short method190(Short paramName0) { return 0; }

  @XLFunction
  public double method191(Long paramName0) { return 0d; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public short method192(Character paramName0, Double paramName1, Object paramName2, MyClass paramName3, Long paramName4, int paramName5, MyEnum paramName6) { return 0; }

  @XLFunction
  public Long method193(Short paramName0, double paramName1, Short paramName2, MyClass paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public long method194(BigDecimal paramName0, Double paramName1, String paramName2) { return 0L; }

  @XLFunction(isAsynchronous=false)
  public void method195(String paramName0, Object paramName1, long paramName2) { return ; }

  @XLFunction(isAsynchronous=false)
  public Integer method196(Double paramName0, String paramName1, String paramName2) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public byte method197(Object paramName0, Float paramName1) { return 0; }

  @XLFunction(isAsynchronous=true)
  public MyClass method198(long paramName0, double paramName1, String paramName2) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Float method199(double paramName0, byte paramName1, LocalDate paramName2) { return null; }

  @XLFunction(isAsynchronous=true)
  public char method200(boolean paramName0, Float paramName1, char paramName2, char paramName3, String paramName4, boolean paramName5) { return 'x'; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Float method201(Boolean paramName0, Short paramName1, float paramName2, String paramName3, MyEnum paramName4, BigInteger paramName5, byte paramName6) { return null; }

  @XLFunction(isAsynchronous=true)
  public Long method202(BigDecimal paramName0) { return null; }

  @XLFunction(isAsynchronous=false)
  public Object method203(Integer paramName0, float paramName1, BigInteger paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public BigDecimal method204() { return null; }

  @XLFunction(isAsynchronous=true)
  public MyClass method205(Integer paramName0, Object paramName1, Object paramName2, Float paramName3, Short paramName4, Boolean paramName5) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public MyClass method206(int paramName0, Integer paramName1, Short paramName2) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public String method207(Object paramName0, byte paramName1, byte paramName2, Float paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Float method208(BigInteger paramName0) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Double method209(MyEnum paramName0, MyEnum paramName1, Double paramName2, Double paramName3) { return null; }

  @XLFunction(isAsynchronous=true)
  public Character method210(short paramName0, double paramName1, short paramName2, boolean paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Boolean method211() { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Object method212(MyClass paramName0, long paramName1, String paramName2) { return null; }

  @XLFunction
  public int method213(Object paramName0, LocalDate paramName1, MyEnum paramName2, char paramName3, MyEnum paramName4, Boolean paramName5) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public Long method214() { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public char method215(Object paramName0, MyEnum paramName1, short paramName2) { return 'x'; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public LocalDate method216(Double paramName0, Integer paramName1) { return null; }

  @XLFunction(isAsynchronous=false)
  public Integer method217(String paramName0, boolean paramName1, BigDecimal paramName2, char paramName3, BigInteger paramName4) { return null; }

  @XLFunction
  public Object method218(Double paramName0) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public void method219(String paramName0, double paramName1, double paramName2, Boolean paramName3) { return ; }

  @XLFunction(isAsynchronous=true)
  public Character method220() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public MyEnum method221(Double paramName0, short paramName1, Integer paramName2, Character paramName3, Double paramName4, BigInteger paramName5) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public Long method222(BigInteger paramName0, float paramName1, byte paramName2) { return null; }

  @XLFunction(isAsynchronous=false)
  public MyClass method223() { return null; }

  @XLFunction
  public byte method224(Integer paramName0, boolean paramName1, Integer paramName2, Byte paramName3, Byte paramName4) { return 0; }

  @XLFunction
  public Byte method225() { return null; }

  @XLFunction(isAsynchronous=false)
  public double method226(Character paramName0, String paramName1, long paramName2, double paramName3, Object paramName4, Short paramName5, Integer paramName6) { return 0d; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Short method227(Short paramName0, MyClass paramName1, Double paramName2, Short paramName3, char paramName4, BigDecimal paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public float method228(int paramName0) { return 0f; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Boolean method229(Float paramName0, Float paramName1, LocalDate paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Object method230(Character paramName0, Boolean paramName1, Long paramName2) { return null; }

  @XLFunction
  public Double method231() { return null; }

  @XLFunction(isAsynchronous=false)
  public BigDecimal method232() { return null; }

  @XLFunction(isAsynchronous=true)
  public Boolean method233(long paramName0, BigInteger paramName1, char paramName2, MyClass paramName3, short paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public MyClass method234(Character paramName0, Long paramName1, Character paramName2, Double paramName3, double paramName4, boolean paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public BigInteger method235(char paramName0, Character paramName1, boolean paramName2, LocalDate paramName3, BigInteger paramName4) { return null; }

  @XLFunction
  public void method236(short paramName0) { return ; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public boolean method237(double paramName0, Integer paramName1, byte paramName2, MyClass paramName3, Short paramName4) { return true; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public BigDecimal method238(boolean paramName0, short paramName1, Character paramName2, BigInteger paramName3, short paramName4, MyClass paramName5) { return null; }

  @XLFunction
  public Integer method239() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public boolean method240(Short paramName0) { return true; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public MyEnum method241(Character paramName0, Object paramName1, double paramName2, float paramName3, Short paramName4) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Long method242(short paramName0, String paramName1, Byte paramName2, Short paramName3) { return null; }

  @XLFunction
  public void method243(Character paramName0, Double paramName1, double paramName2, Double paramName3) { return ; }

  @XLFunction(isAsynchronous=false)
  public Byte method244(LocalDate paramName0, short paramName1, Double paramName2, MyEnum paramName3) { return null; }

  @XLFunction(isAsynchronous=true)
  public String method245(float paramName0, Double paramName1, Float paramName2) { return null; }

  @XLFunction(isAsynchronous=true)
  public MyClass method246(BigInteger paramName0, MyEnum paramName1, Float paramName2, float paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public int method247(MyClass paramName0, int paramName1, boolean paramName2, long paramName3, String paramName4, Boolean paramName5, Object paramName6) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public Integer method248() { return null; }

  @XLFunction
  public MyEnum method249(String paramName0, char paramName1) { return null; }

  @XLFunction(isAsynchronous=false)
  public long method250(long paramName0, int paramName1, Double paramName2, Boolean paramName3, Double paramName4) { return 0L; }

  @XLFunction(isAsynchronous=true)
  public Long method251(float paramName0, boolean paramName1) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public long method252(MyClass paramName0, Double paramName1, short paramName2, MyClass paramName3, MyClass paramName4) { return 0L; }

  @XLFunction
  public BigDecimal method253() { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Boolean method254(char paramName0) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public LocalDate method255(long paramName0, byte paramName1, String paramName2, String paramName3) { return null; }

  @XLFunction(isAsynchronous=true)
  public byte method256(double paramName0, MyClass paramName1, Long paramName2, byte paramName3, Boolean paramName4) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Boolean method257(Boolean paramName0, Short paramName1, int paramName2, Boolean paramName3, MyClass paramName4) { return null; }

  @XLFunction(isAsynchronous=false)
  public MyClass method258(Float paramName0, long paramName1, LocalDate paramName2, String paramName3, Character paramName4, byte paramName5) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public int method259(Double paramName0, Object paramName1, Float paramName2, Integer paramName3) { return 0; }

  @XLFunction(isAsynchronous=true)
  public byte method260(Byte paramName0, long paramName1, Object paramName2, String paramName3, byte paramName4, Byte paramName5, Boolean paramName6) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public boolean method261(Integer paramName0, Character paramName1, Double paramName2, Boolean paramName3, char paramName4, Integer paramName5) { return true; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public BigDecimal method262(LocalDate paramName0) { return null; }

  @XLFunction(isAsynchronous=false)
  public short method263(MyEnum paramName0, Long paramName1, LocalDate paramName2, MyClass paramName3, BigInteger paramName4) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public int method264(Boolean paramName0, Character paramName1, MyClass paramName2) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Object method265(Short paramName0, double paramName1, short paramName2, byte paramName3) { return null; }

  @XLFunction(isAsynchronous=true)
  public Byte method266(String paramName0, Double paramName1, Float paramName2, byte paramName3, long paramName4, Integer paramName5) { return null; }

  @XLFunction
  public short method267(Byte paramName0, long paramName1, double paramName2, byte paramName3, Long paramName4, Double paramName5, String paramName6) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Character method268(BigInteger paramName0, char paramName1, double paramName2, boolean paramName3, short paramName4, Integer paramName5, char paramName6) { return null; }

  @XLFunction(isAsynchronous=false)
  public String method269(LocalDate paramName0, Long paramName1, Object paramName2, double paramName3, int paramName4, BigInteger paramName5, Character paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public Character method270(double paramName0, byte paramName1, MyClass paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public short method271(LocalDate paramName0, MyClass paramName1, boolean paramName2, char paramName3, BigDecimal paramName4, long paramName5, LocalDate paramName6) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Character method272(MyEnum paramName0, Character paramName1, Double paramName2, BigDecimal paramName3) { return null; }

  @XLFunction
  public String method273(char paramName0) { return null; }

  @XLFunction
  public double method274(float paramName0, Integer paramName1, MyClass paramName2, char paramName3, Short paramName4, Double paramName5, Float paramName6) { return 0d; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public MyEnum method275(byte paramName0, Float paramName1, LocalDate paramName2, MyEnum paramName3, int paramName4) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public LocalDate method276(MyClass paramName0, Float paramName1, Float paramName2, LocalDate paramName3, byte paramName4) { return null; }

  @XLFunction
  public BigDecimal method277(Integer paramName0, Short paramName1, double paramName2, BigInteger paramName3, Byte paramName4, int paramName5) { return null; }

  @XLFunction
  public Object method278(long paramName0) { return null; }

  @XLFunction(isAsynchronous=true)
  public Integer method279(Float paramName0, byte paramName1, double paramName2, BigDecimal paramName3) { return null; }

  @XLFunction
  public int method280(Character paramName0, Object paramName1, String paramName2, Byte paramName3, boolean paramName4, long paramName5, LocalDate paramName6) { return 0; }

  @XLFunction
  public Character method281(Character paramName0, boolean paramName1, Float paramName2, MyEnum paramName3, MyClass paramName4) { return null; }

  @XLFunction
  public BigInteger method282(double paramName0, BigDecimal paramName1, MyClass paramName2, Byte paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public String method283(BigDecimal paramName0, Double paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public BigDecimal method284(int paramName0, Float paramName1, boolean paramName2, String paramName3, Integer paramName4) { return null; }

  @XLFunction(isAsynchronous=false)
  public String method285(String paramName0, byte paramName1, Float paramName2, BigDecimal paramName3, Object paramName4, Long paramName5, char paramName6) { return null; }

  @XLFunction(isAsynchronous=true)
  public char method286(Double paramName0, String paramName1, short paramName2, short paramName3, int paramName4, Float paramName5) { return 'x'; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public short method287(Double paramName0, boolean paramName1, byte paramName2, Double paramName3, BigDecimal paramName4) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public BigDecimal method288(LocalDate paramName0, Object paramName1, Short paramName2, Object paramName3) { return null; }

  @XLFunction(isAsynchronous=false)
  public void method289(Byte paramName0, Float paramName1, Double paramName2) { return ; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public int method290(Byte paramName0, LocalDate paramName1, BigInteger paramName2, Short paramName3, BigInteger paramName4, char paramName5) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Short method291(BigInteger paramName0, Integer paramName1, byte paramName2, String paramName3, LocalDate paramName4) { return null; }

  @XLFunction
  public LocalDate method292() { return null; }

  @XLFunction(isAsynchronous=false)
  public Object method293(Float paramName0, Long paramName1, Float paramName2, Float paramName3, boolean paramName4, Long paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public MyEnum method294(short paramName0, Byte paramName1, char paramName2, short paramName3, BigInteger paramName4) { return null; }

  @XLFunction(isAsynchronous=false)
  public BigDecimal method295(LocalDate paramName0, Object paramName1, MyEnum paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public void method296() { return ; }

  @XLFunction
  public char method297(Byte paramName0, Byte paramName1, MyClass paramName2) { return 'x'; }

  @XLFunction(isAsynchronous=true)
  public int method298(byte paramName0, Boolean paramName1, MyClass paramName2, Float paramName3, short paramName4) { return 0; }

  @XLFunction
  public boolean method299(double paramName0, MyClass paramName1, MyClass paramName2, LocalDate paramName3) { return true; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public long method300(LocalDate paramName0, long paramName1, short paramName2, long paramName3) { return 0L; }

  @XLFunction(isAsynchronous=false)
  public boolean method301(LocalDate paramName0, BigInteger paramName1, Float paramName2, Long paramName3, BigInteger paramName4, char paramName5, byte paramName6) { return true; }

  @XLFunction
  public char method302(byte paramName0, char paramName1) { return 'x'; }

  @XLFunction
  public Float method303(Float paramName0, Boolean paramName1, BigInteger paramName2, LocalDate paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public char method304(boolean paramName0, Double paramName1, short paramName2, MyEnum paramName3, Object paramName4) { return 'x'; }

  @XLFunction
  public short method305(Double paramName0) { return 0; }

  @XLFunction
  public char method306(long paramName0, String paramName1, int paramName2, int paramName3, LocalDate paramName4, int paramName5) { return 'x'; }

  @XLFunction(isAsynchronous=false)
  public byte method307(LocalDate paramName0, String paramName1, double paramName2, Object paramName3, String paramName4, Byte paramName5, float paramName6) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Character method308(Short paramName0, Byte paramName1, Long paramName2, byte paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Long method309(boolean paramName0, BigDecimal paramName1, Float paramName2, Double paramName3, LocalDate paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Object method310(char paramName0, double paramName1, Float paramName2, Float paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public String method311() { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public double method312(Byte paramName0, long paramName1, BigDecimal paramName2, String paramName3, float paramName4, char paramName5, long paramName6) { return 0d; }

  @XLFunction
  public char method313() { return 'x'; }

  @XLFunction
  public Double method314(long paramName0, BigInteger paramName1, LocalDate paramName2, Double paramName3, float paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Byte method315(short paramName0, Byte paramName1) { return null; }

  @XLFunction
  public Character method316() { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Short method317(String paramName0, BigDecimal paramName1) { return null; }

  @XLFunction(isAsynchronous=false)
  public Short method318(BigDecimal paramName0, MyClass paramName1, Character paramName2, Double paramName3, Boolean paramName4, int paramName5) { return null; }

  @XLFunction(isAsynchronous=false)
  public short method319(Short paramName0, Long paramName1) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Integer method320(Long paramName0, long paramName1, long paramName2, short paramName3, byte paramName4) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Integer method321(char paramName0, BigInteger paramName1, long paramName2, Byte paramName3, int paramName4) { return null; }

  @XLFunction
  public MyEnum method322(double paramName0, byte paramName1) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public boolean method323() { return true; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public double method324(Integer paramName0, long paramName1, Byte paramName2, double paramName3, boolean paramName4, float paramName5) { return 0d; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Byte method325() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Long method326(short paramName0, BigInteger paramName1) { return null; }

  @XLFunction
  public Boolean method327(Long paramName0, int paramName1, Double paramName2, int paramName3, Boolean paramName4, String paramName5, char paramName6) { return null; }

  @XLFunction(isAsynchronous=false)
  public MyClass method328(long paramName0, float paramName1, Object paramName2) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public BigDecimal method329(MyEnum paramName0, LocalDate paramName1, byte paramName2) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public long method330(long paramName0, byte paramName1, Long paramName2, Boolean paramName3, LocalDate paramName4, char paramName5) { return 0L; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public String method331(MyEnum paramName0, MyClass paramName1, Boolean paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Byte method332(String paramName0, int paramName1, char paramName2, short paramName3, Long paramName4, float paramName5, Short paramName6) { return null; }

  @XLFunction
  public void method333(double paramName0, Long paramName1, BigDecimal paramName2) { return ; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public long method334(boolean paramName0) { return 0L; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Long method335(Boolean paramName0, LocalDate paramName1, MyEnum paramName2, double paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Long method336() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public BigDecimal method337(char paramName0, BigDecimal paramName1, BigDecimal paramName2, int paramName3, short paramName4, boolean paramName5, MyEnum paramName6) { return null; }

  @XLFunction(isAsynchronous=false)
  public MyEnum method338(Object paramName0, BigInteger paramName1, boolean paramName2, int paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Character method339(String paramName0) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Short method340(MyClass paramName0, Long paramName1, Short paramName2, MyEnum paramName3, Double paramName4, Character paramName5) { return null; }

  @XLFunction(isAsynchronous=true)
  public void method341(Short paramName0) { return ; }

  @XLFunction
  public Float method342() { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public int method343(byte paramName0, int paramName1, short paramName2, Short paramName3, Double paramName4) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public MyClass method344(Short paramName0, String paramName1, Long paramName2, double paramName3, BigDecimal paramName4) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public BigDecimal method345(Character paramName0) { return null; }

  @XLFunction(isAsynchronous=true)
  public LocalDate method346(Long paramName0, float paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public MyClass method347(BigDecimal paramName0, MyClass paramName1) { return null; }

  @XLFunction
  public Float method348(Character paramName0, Float paramName1, float paramName2, char paramName3, Integer paramName4) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public Double method349(double paramName0, LocalDate paramName1, Object paramName2, Integer paramName3, Object paramName4) { return null; }

  @XLFunction(isAsynchronous=false)
  public Boolean method350(int paramName0, Float paramName1, BigInteger paramName2) { return null; }

  @XLFunction(isAsynchronous=true)
  public LocalDate method351(int paramName0) { return null; }

  @XLFunction(isAsynchronous=true)
  public MyClass method352(String paramName0, BigDecimal paramName1, Integer paramName2, Boolean paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Byte method353(char paramName0) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Short method354(Short paramName0, Double paramName1, short paramName2, byte paramName3, char paramName4) { return null; }

  @XLFunction
  public Object method355(int paramName0, boolean paramName1, int paramName2, MyEnum paramName3, Object paramName4, Short paramName5) { return null; }

  @XLFunction(isAsynchronous=false)
  public BigInteger method356() { return null; }

  @XLFunction(isAsynchronous=true)
  public Character method357(double paramName0, BigInteger paramName1, Byte paramName2, String paramName3, Long paramName4) { return null; }

  @XLFunction(isAsynchronous=false)
  public Character method358(Object paramName0, Short paramName1, byte paramName2, MyEnum paramName3) { return null; }

  @XLFunction(isAsynchronous=false)
  public BigInteger method359(short paramName0, MyClass paramName1, Boolean paramName2, Integer paramName3, float paramName4) { return null; }

  @XLFunction(isAsynchronous=true)
  public Boolean method360(Object paramName0, Byte paramName1, byte paramName2, long paramName3, byte paramName4) { return null; }

  @XLFunction(isAsynchronous=true)
  public double method361(double paramName0, short paramName1, BigInteger paramName2, String paramName3, char paramName4) { return 0d; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public MyEnum method362(boolean paramName0, Long paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public Short method363(Integer paramName0, BigInteger paramName1, LocalDate paramName2) { return null; }

  @XLFunction
  public short method364(Long paramName0, Object paramName1, int paramName2, Byte paramName3, float paramName4, float paramName5) { return 0; }

  @XLFunction(isAsynchronous=false)
  public String method365(byte paramName0, Byte paramName1, Float paramName2, Boolean paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Float method366(char paramName0, BigDecimal paramName1, String paramName2, Object paramName3, Character paramName4, BigDecimal paramName5, Float paramName6) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public byte method367(Byte paramName0, MyEnum paramName1, Byte paramName2, float paramName3) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public void method368(short paramName0, Object paramName1) { return ; }

  @XLFunction
  public Object method369(char paramName0, int paramName1) { return null; }

  @XLFunction(isAsynchronous=true)
  public int method370(Long paramName0, float paramName1, Integer paramName2, Object paramName3, short paramName4, boolean paramName5, int paramName6) { return 0; }

  @XLFunction(isAsynchronous=false)
  public Character method371(short paramName0, BigInteger paramName1, Byte paramName2) { return null; }

  @XLFunction
  public boolean method372(String paramName0) { return true; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public float method373(LocalDate paramName0, BigDecimal paramName1, Byte paramName2, long paramName3, BigInteger paramName4) { return 0f; }

  @XLFunction
  public Boolean method374(Character paramName0, LocalDate paramName1) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Boolean method375(MyClass paramName0, double paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public short method376(byte paramName0, BigDecimal paramName1) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public BigInteger method377(Character paramName0, char paramName1, long paramName2, Object paramName3, boolean paramName4, Double paramName5) { return null; }

  @XLFunction
  public Integer method378(MyEnum paramName0, Double paramName1, String paramName2, int paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Double method379(MyEnum paramName0, MyClass paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public boolean method380(Integer paramName0, String paramName1, Character paramName2, MyEnum paramName3) { return true; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Character method381(long paramName0) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public short method382(long paramName0, Short paramName1, Character paramName2, float paramName3, byte paramName4, double paramName5) { return 0; }

  @XLFunction
  public Object method383(Long paramName0, Boolean paramName1, Float paramName2, int paramName3, Object paramName4, Double paramName5) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public byte method384(Byte paramName0, Byte paramName1) { return 0; }

  @XLFunction
  public Float method385() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public byte method386(float paramName0, short paramName1) { return 0; }

  @XLFunction(isAsynchronous=false)
  public String method387(BigDecimal paramName0, boolean paramName1, MyEnum paramName2, Character paramName3, Float paramName4) { return null; }

  @XLFunction(isAsynchronous=false)
  public Boolean method388(Boolean paramName0, char paramName1) { return null; }

  @XLFunction(isAsynchronous=false)
  public Byte method389(byte paramName0, LocalDate paramName1, Short paramName2, BigInteger paramName3) { return null; }

  @XLFunction(isAsynchronous=false)
  public void method390() { return ; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public int method391(Byte paramName0, Short paramName1, char paramName2, String paramName3, Short paramName4, boolean paramName5, char paramName6) { return 0; }

  @XLFunction
  public String method392(float paramName0, long paramName1, int paramName2, int paramName3) { return null; }

  @XLFunction(isAsynchronous=true)
  public BigInteger method393(LocalDate paramName0, Long paramName1, BigInteger paramName2, Object paramName3, Short paramName4, Short paramName5) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public LocalDate method394(long paramName0, Long paramName1, float paramName2, Byte paramName3, MyEnum paramName4) { return null; }

  @XLFunction
  public short method395(Object paramName0, byte paramName1, String paramName2) { return 0; }

  @XLFunction
  public short method396(Short paramName0, Boolean paramName1, Double paramName2, BigDecimal paramName3, BigDecimal paramName4) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public MyEnum method397(Long paramName0, float paramName1, int paramName2, Short paramName3) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public long method398(Long paramName0, BigInteger paramName1, MyEnum paramName2, long paramName3, Float paramName4) { return 0L; }

  @XLFunction(isAsynchronous=true)
  public void method399(char paramName0, Integer paramName1, int paramName2) { return ; }

  @XLFunction(isAsynchronous=false)
  public Byte method400(Character paramName0, double paramName1) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public byte method401(Byte paramName0, byte paramName1) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public int method402(int paramName0) { return 0; }

  @XLFunction(isAsynchronous=true)
  public float method403(char paramName0, String paramName1, Integer paramName2, short paramName3) { return 0f; }

  @XLFunction
  public Integer method404(MyEnum paramName0, Byte paramName1, boolean paramName2, Double paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public long method405() { return 0L; }

  @XLFunction
  public long method406(Object paramName0, Boolean paramName1) { return 0L; }

  @XLFunction
  public MyEnum method407() { return null; }

  @XLFunction(isAsynchronous=true)
  public double method408() { return 0d; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Double method409(Double paramName0, short paramName1, char paramName2, Float paramName3, MyEnum paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public MyClass method410(Object paramName0, Double paramName1, Byte paramName2, int paramName3, char paramName4, Byte paramName5) { return null; }

  @XLFunction(isAsynchronous=false)
  public BigInteger method411(boolean paramName0, short paramName1, byte paramName2, byte paramName3, Float paramName4, char paramName5, Float paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Byte method412(short paramName0, LocalDate paramName1, short paramName2, MyEnum paramName3, MyEnum paramName4, BigDecimal paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Short method413(MyEnum paramName0, Float paramName1, Float paramName2, char paramName3, Long paramName4, Boolean paramName5, Double paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public BigDecimal method414(long paramName0, Long paramName1, int paramName2, MyEnum paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public MyClass method415(float paramName0, Float paramName1, LocalDate paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public String method416(LocalDate paramName0, Double paramName1, BigInteger paramName2, Boolean paramName3, Double paramName4) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public Float method417(BigDecimal paramName0, short paramName1, char paramName2, Short paramName3, Double paramName4, Boolean paramName5, MyClass paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public Long method418(double paramName0, Byte paramName1, BigInteger paramName2, Integer paramName3, float paramName4) { return null; }

  @XLFunction
  public MyEnum method419(Character paramName0, Integer paramName1, MyClass paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Byte method420(Long paramName0, byte paramName1, Float paramName2, String paramName3, Byte paramName4, BigDecimal paramName5, Short paramName6) { return null; }

  @XLFunction(isAsynchronous=false)
  public Float method421() { return null; }

  @XLFunction
  public MyClass method422(double paramName0, boolean paramName1, char paramName2, Short paramName3, Integer paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Long method423(Boolean paramName0, String paramName1, boolean paramName2, BigInteger paramName3, short paramName4, boolean paramName5) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Double method424(String paramName0, float paramName1, Float paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public boolean method425(BigInteger paramName0, String paramName1, Integer paramName2, Byte paramName3, BigDecimal paramName4, char paramName5, Float paramName6) { return true; }

  @XLFunction(isAsynchronous=false)
  public short method426(char paramName0, MyClass paramName1, byte paramName2, long paramName3, BigInteger paramName4, Float paramName5) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Long method427(Integer paramName0, byte paramName1, LocalDate paramName2, short paramName3) { return null; }

  @XLFunction
  public long method428(Object paramName0, int paramName1, Integer paramName2, Double paramName3, String paramName4, char paramName5) { return 0L; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public Double method429(MyClass paramName0, Double paramName1, byte paramName2, Long paramName3, String paramName4) { return null; }

  @XLFunction(isAsynchronous=true)
  public BigDecimal method430(Long paramName0, LocalDate paramName1, Boolean paramName2, Integer paramName3, MyClass paramName4, Object paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public double method431(Object paramName0, char paramName1, LocalDate paramName2, Byte paramName3, double paramName4, long paramName5, byte paramName6) { return 0d; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public MyClass method432(int paramName0, MyClass paramName1, boolean paramName2, BigInteger paramName3) { return null; }

  @XLFunction
  public float method433(BigDecimal paramName0, boolean paramName1, Double paramName2) { return 0f; }

  @XLFunction(isAsynchronous=true)
  public MyClass method434(Float paramName0, BigDecimal paramName1, long paramName2, Object paramName3, char paramName4) { return null; }

  @XLFunction
  public MyClass method435(float paramName0, long paramName1, Boolean paramName2, String paramName3, BigDecimal paramName4, Float paramName5) { return null; }

  @XLFunction
  public MyEnum method436(MyEnum paramName0) { return null; }

  @XLFunction
  public char method437(Boolean paramName0, Boolean paramName1, MyEnum paramName2, char paramName3, Float paramName4) { return 'x'; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public BigInteger method438(LocalDate paramName0, Long paramName1, byte paramName2, Double paramName3, Double paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Object method439() { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public BigDecimal method440(Short paramName0, Character paramName1, Character paramName2, Double paramName3) { return null; }

  @XLFunction
  public String method441(char paramName0, Character paramName1, Byte paramName2, Object paramName3, Float paramName4, double paramName5, long paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public String method442(char paramName0) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Boolean method443() { return null; }

  @XLFunction(isAsynchronous=false)
  public Integer method444(double paramName0) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public float method445(Float paramName0, MyClass paramName1, Object paramName2, LocalDate paramName3, BigInteger paramName4, Long paramName5, double paramName6) { return 0f; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public short method446(float paramName0, double paramName1, Character paramName2, double paramName3, String paramName4) { return 0; }

  @XLFunction(isAsynchronous=true)
  public Double method447(MyEnum paramName0, String paramName1, float paramName2, String paramName3) { return null; }

  @XLFunction(isAsynchronous=false)
  public LocalDate method448(LocalDate paramName0, int paramName1, MyEnum paramName2, String paramName3, Object paramName4, MyClass paramName5, boolean paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public LocalDate method449() { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Object method450(long paramName0) { return null; }

  @XLFunction(isAsynchronous=false)
  public void method451(MyEnum paramName0, float paramName1, Integer paramName2, double paramName3, long paramName4, float paramName5) { return ; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public Object method452(Integer paramName0, MyClass paramName1, BigDecimal paramName2, MyClass paramName3, Boolean paramName4, Double paramName5, Float paramName6) { return null; }

  @XLFunction(isAsynchronous=false)
  public LocalDate method453(BigInteger paramName0, Double paramName1, Character paramName2) { return null; }

  @XLFunction(isAsynchronous=false)
  public short method454(LocalDate paramName0, Short paramName1, double paramName2) { return 0; }

  @XLFunction
  public Object method455(Float paramName0, Boolean paramName1, BigDecimal paramName2, Byte paramName3) { return null; }

  @XLFunction(isAsynchronous=false)
  public double method456(boolean paramName0, char paramName1, Boolean paramName2, Integer paramName3, byte paramName4) { return 0d; }

  @XLFunction(isAsynchronous=false)
  public Double method457(MyClass paramName0) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public char method458() { return 'x'; }

  @XLFunction(isAsynchronous=false)
  public Boolean method459(Byte paramName0, Integer paramName1, long paramName2, long paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=true)
  public String method460(MyEnum paramName0, boolean paramName1, char paramName2, char paramName3, MyClass paramName4, Byte paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public byte method461(boolean paramName0, Short paramName1, LocalDate paramName2, int paramName3, Boolean paramName4, double paramName5) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public MyEnum method462(int paramName0, Integer paramName1, byte paramName2, MyClass paramName3, boolean paramName4) { return null; }

  @XLFunction
  public String method463(float paramName0, int paramName1, BigDecimal paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public short method464(Byte paramName0, Double paramName1, BigInteger paramName2, short paramName3, Float paramName4) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true)
  public short method465() { return 0; }

  @XLFunction(isAsynchronous=false)
  public MyEnum method466(char paramName0, short paramName1) { return null; }

  @XLFunction
  public Integer method467() { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public BigInteger method468(MyEnum paramName0, Object paramName1) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public double method469(Long paramName0, double paramName1, byte paramName2, float paramName3) { return 0d; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=false)
  public short method470(Byte paramName0, Float paramName1, Short paramName2, Integer paramName3, Object paramName4, char paramName5, Boolean paramName6) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=true, isMultiThreadSafe=true)
  public byte method471(Double paramName0, Double paramName1, String paramName2, Float paramName3) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public Character method472(Boolean paramName0, MyClass paramName1, Double paramName2, Character paramName3, LocalDate paramName4, BigInteger paramName5, byte paramName6) { return null; }

  @XLFunction
  public Float method473(Integer paramName0, int paramName1, Double paramName2, byte paramName3, byte paramName4, byte paramName5, Long paramName6) { return null; }

  @XLFunction
  public Short method474() { return null; }

  @XLFunction(isAsynchronous=true)
  public byte method475(int paramName0, long paramName1, BigInteger paramName2, Integer paramName3, MyEnum paramName4) { return 0; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public MyEnum method476(String paramName0, int paramName1) { return null; }

  @XLFunction
  public MyClass method477(MyEnum paramName0, String paramName1, Byte paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public Float method478(String paramName0, LocalDate paramName1, BigDecimal paramName2, Long paramName3, Byte paramName4, float paramName5, float paramName6) { return null; }

  @XLFunction(isAsynchronous=true)
  public double method479(double paramName0, Character paramName1, double paramName2) { return 0d; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public Float method480(BigDecimal paramName0, int paramName1, Byte paramName2, Object paramName3, String paramName4, Byte paramName5) { return null; }

  @XLFunction
  public LocalDate method481(MyClass paramName0, BigInteger paramName1, MyClass paramName2, int paramName3, Short paramName4, String paramName5) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public BigInteger method482(Character paramName0, LocalDate paramName1, BigDecimal paramName2, Integer paramName3, boolean paramName4, char paramName5) { return null; }

  @XLFunction(isAsynchronous=true)
  public long method483(LocalDate paramName0, float paramName1, double paramName2) { return 0L; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=true)
  public void method484(MyEnum paramName0, boolean paramName1, MyEnum paramName2) { return ; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public BigDecimal method485(short paramName0, Boolean paramName1, Double paramName2, Double paramName3, LocalDate paramName4, Float paramName5, Short paramName6) { return null; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public BigInteger method486() { return null; }

  @XLFunction(isAsynchronous=true)
  public BigInteger method487(boolean paramName0, BigInteger paramName1, Long paramName2) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public float method488(float paramName0, BigInteger paramName1, char paramName2, boolean paramName3, Long paramName4) { return 0f; }

  @XLFunction(isAsynchronous=true)
  public LocalDate method489(Byte paramName0, byte paramName1, Character paramName2, Byte paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Short method490(double paramName0, Double paramName1, Object paramName2, Integer paramName3, LocalDate paramName4) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=true)
  public MyEnum method491(String paramName0, boolean paramName1, Short paramName2, float paramName3, Integer paramName4, Object paramName5) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=false)
  public long method492(Boolean paramName0, String paramName1) { return 0L; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false, isMultiThreadSafe=false)
  public Byte method493(char paramName0, Object paramName1, boolean paramName2, Byte paramName3) { return null; }

  @XLFunction
  public int method494(Object paramName0, double paramName1) { return 0; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public MyClass method495(MyEnum paramName0, char paramName1, long paramName2, LocalDate paramName3, MyEnum paramName4) { return null; }

  @XLFunction
  public double method496(Object paramName0, String paramName1, MyEnum paramName2, float paramName3, LocalDate paramName4, int paramName5) { return 0d; }

  @XLFunction(isAsynchronous=false, isMacroEquivalent=false)
  public long method497(byte paramName0, short paramName1, boolean paramName2, Object paramName3, Float paramName4) { return 0L; }

  @XLFunction(isAsynchronous=true)
  public Object method498(LocalDate paramName0, short paramName1, Byte paramName2, BigDecimal paramName3) { return null; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true)
  public Double method499() { return null; }

  @XLFunction
  public Short method500(Short paramName0, Character paramName1, MyEnum paramName2, short paramName3, int paramName4, MyEnum paramName5) { return null; }

  @XLFunction
  public BigDecimal method501(Integer paramName0) { return null; }

  @XLFunction(isAsynchronous=true)
  public float method502(Boolean paramName0, double paramName1, float paramName2, Boolean paramName3, LocalDate paramName4) { return 0f; }

  @XLFunction(isAsynchronous=true, isMacroEquivalent=true, isMultiThreadSafe=false)
  public char method503(Byte paramName0, LocalDate paramName1) { return 'x'; }

  @XLFunction(isAsynchronous=true)
  public String method504() { return null; }

  @XLFunction(isAsynchronous=true)
  public Float method505(Long paramName0, Long paramName1, float paramName2, Float paramName3, MyEnum paramName4) { return null; }

  @XLFunction
  public long method506() { return 0L; }

  @XLFunction
  public byte method507() { return 0; }

  @XLFunction
  public Integer method508(short paramName0, Integer paramName1, Float paramName2, char paramName3, Long paramName4) { return null; }

  @XLFunction
  public BigInteger method509(Short paramName0, double paramName1, Double paramName2, Byte paramName3, MyClass paramName4, char paramName5, Integer paramName6) { return null; }

  @XLFunction
  public long method510(long paramName0, int paramName1, byte paramName2) { return 0L; }

  @XLFunction
  public short method511(MyClass paramName0, Double paramName1, double paramName2, long paramName3, Long paramName4, char paramName5) { return 0; }

  
  // CHECKSTYLE:ON
}
